elasticsearch:
  host: 127.0.0.1
  port: 9200

# datasource
spring:
  datasource:
    url: jdbc:mysql://192.168.137.123:3306/es?serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.atguigu.domain
