server:
  port: 8888

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/books
    username: root
    password: root

mybatis:
  mapperLocations: /mapper/*.xml
  type-aliases-package: com.dilo.springcloud.bean


eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
